version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8081:80'
    network_mode: bridge
    external_links:
      - KyLibraryDB
    environment:
      PGADMIN_DEFAULT_EMAIL: kylibrary@kybox.fr
      PGADMIN_DEFAULT_PASSWORD: kylibrary:admin-db
